name: Pre-release Github

on:
  push:
    branches:
      - "release/2.x.x"

jobs:
  pre-release:
    runs-on: macos-latest

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "prevMajorLatest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.jar
